# Generated by Django 4.1.2 on 2022-10-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_itemcategory_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
