# Generated by Django 4.1.2 on 2022-10-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'NonVeg')], default='nonveg', max_length=20),
        ),
    ]
