# Generated by Django 4.1.2 on 2022-10-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_itemcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
