# Generated by Django 4.1.2 on 2022-11-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
