# Generated by Django 4.1.2 on 2022-11-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_cart'),
        ('order', '0006_remove_order_item_remove_order_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.cart'),
        ),
    ]
