# Generated by Django 4.1.2 on 2022-11-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutaddress',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
    ]
