# Generated by Django 4.1.2 on 2022-11-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_checkoutaddress_first_name_checkoutaddress_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
